spring:
  data:
    mongodb:
      username: maxi
      password: maxi
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.maxiflexy.ecommerce.order.kafka.OrderConfirmation,paymentConfirmation:com.maxiflexy.ecommerce.payment.dto.PaymentNotificationRequest
  mail:
    host: localhost
    port: 1025
    username: maxi
    password: maxi
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

server:
  port: 8040